### ISSUE TITLE
Hardcoded "IsMobile" instead of property name in GettingStarted example

### ISSUE THREAD

**Issue by kazuhiro** [51Degrees/device-detection-cxx#13]
I think this line should refer to `propertyName` instead of `"IsMobile"`:

https://github.com/51Degrees/device-detection-cxx/blob/e04f68e237aeb6fdb3a252ed84ff3ae2962c0aac/examples/C/Hash/GettingStarted.c#L120

**Comment by jwrosewell** [comment]
We agree. This will need to be scheduled for a future release. Thank you for raising.
