### ISSUE TITLE
Tests are failing due to missing files in device-detection-data

### ISSUE THREAD

**Issue by kazuhiro** [51Degrees/device-detection-cxx#48]
`device-detection-data` subproject does not contain `TAC` and `Enterprise` files so it is impossible to successfully run test suite for `device-detection-cxx` library after simple checkout.

**Comment by Sara51D** [comment]
Hi @kazuhiro , Thank you for bringing this up - Indeed the tests that depend on enterprise data file should be skipped when the file is missing.  We'll need to do a slight refactoring to our tests to explicitly introduce this behavior and we hope to address this in the near future.
