### ISSUE TITLE
Return string references vs allocating?

### ISSUE THREAD

**Issue by parisholley** [51Degrees/device-detection-cxx#8]
https://github.com/51Degrees/device-detection-cxx/blob/214a7663337e7f6af5a0c9291a6f94ea7919d0b4/src/hash/ResultsHash.cpp#L94

I think part of the reason for the poor string performance I am seeing. assuming I understand this code correctly, is that every time a ResultHash is built for a user agent lookup, if the user requests a property via valueAsString, instead of passing a string reference/pointer back, it is allocating a copy of it each time. is there a reason we couldn't just let the client/consumer decide if they need a string object they own vs a reference/pointer?

or perhaps it would be less breaking to introduce a valueAsStringPtr?

in rust, we have String and &str, and it would be cheaper to interface with the this library over FFI if it isn't having to allocate strings each call.

**Comment by ben51degrees** [comment]
Hi @parisholley ,
The reasoning behind allocating the string on the stack is the types of collections we need to support.
The strings come from internal collections which can be configured differently. If they are configured to be all in memory, then you're absolutely correct, and we can return the string directly. However, if the collection is being read from disk it is allocated in the heap, meaning that the caller has the responsibility of freeing it. To avoid passing this responsibility to other languages which call the C++ classes (which can become very complicated), the string is copied to the stack.

I think your suggestion of an `asPtr` method is the best way forward. It should be made clear in the documentation around this that it should be used either in memory only configuration, or very carefully, to avoid issues if people are using the streaming configuration.

I will raise this with the team and get back to you with a decision on if/when this will be implemented.

Thanks,
Ben.

**Comment by parisholley** [comment]
makes sense. i'm already working with a fork of common and cxx, so i'd be happy to look into implementing a ptr version

**Comment by ben51degrees** [comment]
Thanks @parisholley . If you make a pull request for it I'm happy to review it.
And if you have any questions on the code, do let me know

**Comment by parisholley** [comment]
closing this, realized i'm better off integrating with the c library and wrote a shim to access the ptr's directly
